from .auth import (
    DashboardView,
    HomeView,
    RegistroView,
    SpotterLoginView,
    SpotterLogoutView,
)
from .aluno import (
    AlunoAvaliacaoView,
    AlunoBuscarPersonalView,
    AlunoContratoListView,
    AlunoExercicioDetailView,
    AlunoFeedbackExercicioView,
    AlunoFeedbackSessaoView,
    AlunoPersonalDetailView,
    AlunoPlanoDetailView,
    AlunoPlanoListView,
    AlunoSessaoDetailView,
    AlunoSolicitarContratoView,
)
from .contrato import (
    ContratoCreateView,
    redirecionar_ativo,
    detalhe as contrato_detalhe,
)
from .personal import (
    PersonalAceitarContratoView,
    PersonalContratoListView,
    PersonalRecusarContratoView,
    PersonalEncerrarContratoView,
    PersonalAlunoListView,
    PersonalAlunoDetailView,
    PersonalPlanoListView,
    PersonalPlanoDetailView,
    PersonalPlanoCreateView,
    PersonalPlanoUpdateView,
    PersonalDashboardView,
    plano_detalhe,
    sessao_detalhe,
    exercicio_detalhe,
    SessaoCreateView,
    SessaoDeleteView,
    ExercicioCreateView,
    ExercicioDeleteView,
)

__all__ = [
    "HomeView",
    "RegistroView",
    "SpotterLoginView",
    "SpotterLogoutView",
    "DashboardView",
    # Personal class-based views
    "PersonalContratoListView",
    "PersonalAceitarContratoView",
    "PersonalRecusarContratoView",
    "PersonalEncerrarContratoView",
    "PersonalAlunoListView",
    "PersonalAlunoDetailView",
    "PersonalPlanoListView",
    "PersonalPlanoDetailView",
    "PersonalPlanoCreateView",
    "PersonalPlanoUpdateView",
    "PersonalDashboardView",
    # Personal function-based hierarchy views
    "plano_detalhe",
    "sessao_detalhe",
    "exercicio_detalhe",
    "SessaoCreateView",
    "SessaoDeleteView",
    "ExercicioCreateView",
    "ExercicioDeleteView",
    # Aluno views
    "AlunoContratoListView",
    "AlunoBuscarPersonalView",
    "AlunoPersonalDetailView",
    "AlunoSolicitarContratoView",
    "AlunoPlanoListView",
    "AlunoPlanoDetailView",
    "AlunoSessaoDetailView",
    "AlunoExercicioDetailView",
    "AlunoFeedbackSessaoView",
    "AlunoFeedbackExercicioView",
    "AlunoAvaliacaoView",
    # Contrato views
    "ContratoCreateView",
    "redirecionar_ativo",
    "contrato_detalhe",
]
