# Generated by Django 6.0.5 on 2026-05-21 23:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno'), ('personal', 'Personal Trainer'), ('admin', 'Administrador')], default='aluno', max_length=10)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos', models.TextField(blank=True)),
                ('nivel_condicionamento', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=15)),
                ('historico_lesoes', models.TextField(blank=True)),
                ('restricoes_fisicas', models.TextField(blank=True)),
                ('disponibilidade', models.TextField(blank=True, help_text='Ex: manhãs, seg/qua/sex')),
                ('usuario', models.OneToOneField(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Aluno',
                'verbose_name_plural': 'Perfis Aluno',
            },
        ),
        migrations.CreateModel(
            name='PerfilPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cref', models.CharField(max_length=20, unique=True)),
                ('especialidades', models.TextField(blank=True, help_text='Ex: musculação, funcional, pilates')),
                ('bio', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('avaliacao_media', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('usuario', models.OneToOneField(limit_choices_to={'tipo': 'personal'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Personal',
                'verbose_name_plural': 'Perfis Personal',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('encerrado', 'Encerrado')], default='pendente', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_aluno', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.perfilpersonal')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='core.contrato')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='core.perfilpersonal')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='PlanoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='core.contrato')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_criados', to='core.perfilpersonal')),
            ],
            options={
                'verbose_name': 'Plano de Treino',
                'verbose_name_plural': 'Planos de Treino',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado_em', models.DateTimeField()),
                ('observacoes_aluno', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='historico_treinos', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='core.planotreino')),
            ],
            options={
                'verbose_name': 'Histórico de Treino',
                'verbose_name_plural': 'Histórico de Treinos',
                'ordering': ['-realizado_em'],
            },
        ),
        migrations.CreateModel(
            name='SessaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Treino A – Peito e Tríceps', max_length=100)),
                ('dia_semana', models.CharField(blank=True, choices=[('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=3)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='core.planotreino')),
            ],
            options={
                'verbose_name': 'Sessão de Treino',
                'verbose_name_plural': 'Sessões de Treino',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('series', models.PositiveSmallIntegerField(help_text='Número de séries', validators=[django.core.validators.MinValueValidator(1)])),
                ('repeticoes', models.PositiveSmallIntegerField(help_text='Número de repetições por série', validators=[django.core.validators.MinValueValidator(1)])),
                ('carga', models.CharField(blank=True, help_text='Ex: 20kg, peso corporal', max_length=50)),
                ('duracao_seg', models.PositiveIntegerField(blank=True, help_text='Duração em segundos (para exercícios isométricos/cardio)', null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='core.sessaotreino')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativo')), fields=('aluno', 'personal'), name='unique_contrato_ativo_por_par'),
        ),
    ]
