# Generated by Django 6.0.5 on 2026-05-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercicioPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('grupo_muscular', models.CharField(blank=True, choices=[('peito', 'Peito'), ('costas', 'Costas'), ('pernas', 'Pernas'), ('ombros', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('antebraco', 'Antebraço'), ('abdomen', 'Abdômen'), ('cardio', 'Cardio'), ('funcional', 'Funcional')], max_length=20)),
                ('series_padrao', models.PositiveSmallIntegerField(default=3)),
                ('repeticoes_padrao', models.PositiveSmallIntegerField(default=12)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercício Padrão',
                'verbose_name_plural': 'Exercícios Padrão',
                'ordering': ['grupo_muscular', 'nome'],
                'unique_together': {('nome', 'grupo_muscular')},
            },
        ),
    ]
