# Generated by Django 6.0.5 on 2026-06-19 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exerciciopadrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotreino',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_treino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planotreino',
            name='numero',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('recusado', 'Recusado')], default='pendente', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='planotreino',
            constraint=models.UniqueConstraint(fields=('aluno', 'numero'), name='unique_plano_numero_por_aluno'),
        ),
    ]
