# Generated by Django 6.0.5 on 2026-07-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicotreino',
            name='plano',
        ),
        migrations.AddField(
            model_name='historicotreino',
            name='sessao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='core.sessaotreino'),
        ),
    ]
